// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: namespace.proto

package mu_micro_srv_namespace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Namespace service

type NamespaceService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Namespace_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Namespace_PingPongService, error)
}

type namespaceService struct {
	c    client.Client
	name string
}

func NewNamespaceService(name string, c client.Client) NamespaceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "mu.micro.srv.namespace"
	}
	return &namespaceService{
		c:    c,
		name: name,
	}
}

func (c *namespaceService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Namespace.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Namespace_StreamService, error) {
	req := c.c.NewRequest(c.name, "Namespace.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &namespaceServiceStream{stream}, nil
}

type Namespace_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type namespaceServiceStream struct {
	stream client.Stream
}

func (x *namespaceServiceStream) Close() error {
	return x.stream.Close()
}

func (x *namespaceServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *namespaceServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *namespaceServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *namespaceService) PingPong(ctx context.Context, opts ...client.CallOption) (Namespace_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Namespace.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &namespaceServicePingPong{stream}, nil
}

type Namespace_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type namespaceServicePingPong struct {
	stream client.Stream
}

func (x *namespaceServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *namespaceServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *namespaceServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *namespaceServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *namespaceServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Namespace service

type NamespaceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Namespace_StreamStream) error
	PingPong(context.Context, Namespace_PingPongStream) error
}

func RegisterNamespaceHandler(s server.Server, hdlr NamespaceHandler, opts ...server.HandlerOption) error {
	type namespace interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Namespace struct {
		namespace
	}
	h := &namespaceHandler{hdlr}
	return s.Handle(s.NewHandler(&Namespace{h}, opts...))
}

type namespaceHandler struct {
	NamespaceHandler
}

func (h *namespaceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.NamespaceHandler.Call(ctx, in, out)
}

func (h *namespaceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.NamespaceHandler.Stream(ctx, m, &namespaceStreamStream{stream})
}

type Namespace_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type namespaceStreamStream struct {
	stream server.Stream
}

func (x *namespaceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *namespaceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *namespaceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *namespaceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *namespaceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.NamespaceHandler.PingPong(ctx, &namespacePingPongStream{stream})
}

type Namespace_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type namespacePingPongStream struct {
	stream server.Stream
}

func (x *namespacePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *namespacePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *namespacePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *namespacePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *namespacePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
