version: '3'
services:
  webuserprj:
    build: ./userwebPRJ
    depends_on:
      - consul4
      #- config-manager
    container_name: webusercontianer
    environment:
      RUN_DOCKER_MODE: "on"
    ports:
      - "8080:8080"
#    tty: true
    #开始进行consul集群服务
  config-manager:
    build: ./consul-manager
    depends_on:
      - consul4
    environment:
      RUN_DOCKER_MODE: "on"
  user-srv:
    build: ./user-srv
    environment:
      RUN_DOCKER_MODE: "on"
    depends_on:
      - mysql_db
      - redis
      - config-manager
    links:
      - mysql_db
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mysql_db:
    image: "mysql:latest"
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "${HOME}/mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
  consul1:
    image: consul
    container_name: node1
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
  consul2:
    image: consul
    container_name: node2
    command: agent -server -retry-join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  consul3:
    image: consul
    container_name: node3
    command: agent -server -retry-join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  consul4:
    image: consul
    container_name: node4
    command: agent -retry-join=node1 -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3


